language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1 WP_TRAVISCI=travis:codecoverage

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm install
  - composer install

script:
  - grunt phpcs
  - |
    if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
      phpunit --coverage-clover build/logs/clover.xml
    else:
      phpunit
    fi

after_script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
      bash <(curl -s https://codecov.io/bash)
    fi
